version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vickoman
      POSTGRES_PASSWORD: Mm0925163347
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    container_name: postgresql-vck

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: vickoman.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Mm0925163347
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  local_pgdata:
  pgadmin-data:
